"""Initial authentication schema migration

Revision ID: 001_auth_schema
Revises: 
Create Date: 2026-08-03 10:57:45.349948+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_auth_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_password_hash', sa.Text(), nullable=True),
    sa.Column('user_first_name', sa.String(length=100), nullable=True),
    sa.Column('user_last_name', sa.String(length=100), nullable=True),
    sa.Column('user_profile_image', sa.Text(), nullable=True),
    sa.Column('user_phone', sa.String(length=20), nullable=True),
    sa.Column('user_email_verified', sa.Boolean(), nullable=False),
    sa.Column('user_status', sa.Enum('active', 'suspended', 'deleted', name='user_status_enum'), nullable=False),
    sa.Column('user_last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_tbl_users_user_email'), 'tbl_users', ['user_email'], unique=True)
    op.create_table('tbl_oauth_accounts',
    sa.Column('oauth_account_id', sa.UUID(), nullable=False),
    sa.Column('oauth_account_user_id', sa.UUID(), nullable=False),
    sa.Column('oauth_account_provider', sa.Enum('google', 'github', name='oauth_provider_enum'), nullable=False),
    sa.Column('oauth_account_provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('oauth_account_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oauth_account_user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oauth_account_id'),
    sa.UniqueConstraint('oauth_account_provider', 'oauth_account_provider_user_id', name='uq_provider_user_id')
    )
    op.create_table('tbl_refresh_tokens',
    sa.Column('refresh_token_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_token_id')
    )
    op.create_index(op.f('ix_tbl_refresh_tokens_refresh_token_hash'), 'tbl_refresh_tokens', ['refresh_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_refresh_tokens_refresh_token_hash'), table_name='tbl_refresh_tokens')
    op.drop_table('tbl_refresh_tokens')
    op.drop_table('tbl_oauth_accounts')
    op.drop_index(op.f('ix_tbl_users_user_email'), table_name='tbl_users')
    op.drop_table('tbl_users')
    # ### end Alembic commands ###
