"""Add organizations schema

Revision ID: 002_organizations_schema
Revises: 001_auth_schema
Create Date: 2026-08-03 11:02:16.762036+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_organizations_schema'
down_revision: Union[str, Sequence[str], None] = '001_auth_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_organizations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_slug', sa.String(length=255), nullable=False),
    sa.Column('organization_logo', sa.Text(), nullable=True),
    sa.Column('organization_description', sa.Text(), nullable=True),
    sa.Column('organization_owner_user_id', sa.UUID(), nullable=False),
    sa.Column('organization_status', sa.Enum('active', 'suspended', name='organization_status_enum'), nullable=False),
    sa.Column('organization_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_owner_user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_index(op.f('ix_tbl_organizations_organization_slug'), 'tbl_organizations', ['organization_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_organizations_organization_slug'), table_name='tbl_organizations')
    op.drop_table('tbl_organizations')
    # ### end Alembic commands ###
