"""Add onboarding schema

Revision ID: 003_onboarding_schema
Revises: 002_organizations_schema
Create Date: 2026-08-03 11:27:53.042863+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_onboarding_schema'
down_revision: Union[str, Sequence[str], None] = '002_organizations_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_organization_id', sa.UUID(), nullable=True),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('role_is_system', sa.Boolean(), nullable=False),
    sa.Column('role_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_organization_id'], ['tbl_organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('tbl_workspaces',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('workspace_organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_name', sa.String(length=255), nullable=False),
    sa.Column('workspace_description', sa.Text(), nullable=True),
    sa.Column('workspace_banner', sa.Text(), nullable=True),
    sa.Column('workspace_status', sa.Enum('active', 'archived', name='workspace_status_enum'), nullable=False),
    sa.Column('workspace_created_by', sa.UUID(), nullable=False),
    sa.Column('workspace_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_created_by'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_organization_id'], ['tbl_organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('tbl_organization_members',
    sa.Column('organization_member_id', sa.UUID(), nullable=False),
    sa.Column('organization_member_organization_id', sa.UUID(), nullable=False),
    sa.Column('organization_member_user_id', sa.UUID(), nullable=False),
    sa.Column('organization_member_role_id', sa.UUID(), nullable=False),
    sa.Column('organization_member_status', sa.Enum('pending', 'active', 'suspended', name='org_member_status_enum'), nullable=False),
    sa.Column('organization_member_joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_member_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_member_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_member_organization_id'], ['tbl_organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_member_role_id'], ['tbl_roles.role_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_member_user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_member_id'),
    sa.UniqueConstraint('organization_member_user_id', 'organization_member_organization_id', name='uq_org_member')
    )
    op.create_table('tbl_workspace_members',
    sa.Column('workspace_member_id', sa.UUID(), nullable=False),
    sa.Column('workspace_member_workspace_id', sa.UUID(), nullable=False),
    sa.Column('workspace_member_user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_member_role_id', sa.UUID(), nullable=False),
    sa.Column('workspace_member_joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_member_role_id'], ['tbl_roles.role_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_member_user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_member_workspace_id'], ['tbl_workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_member_id'),
    sa.UniqueConstraint('workspace_member_workspace_id', 'workspace_member_user_id', name='uq_workspace_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_workspace_members')
    op.drop_table('tbl_organization_members')
    op.drop_table('tbl_workspaces')
    op.drop_table('tbl_roles')
    # ### end Alembic commands ###
