"""Add geo columns to organization

Revision ID: 004_org_geo_columns
Revises: 003_onboarding_schema
Create Date: 2026-08-03 11:38:11.936686+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_org_geo_columns'
down_revision: Union[str, Sequence[str], None] = '003_onboarding_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_organizations', sa.Column('organization_type', sa.String(length=100), nullable=False))
    op.add_column('tbl_organizations', sa.Column('organization_country', sa.String(length=100), nullable=False))
    op.add_column('tbl_organizations', sa.Column('organization_state', sa.String(length=100), nullable=False))
    op.add_column('tbl_organizations', sa.Column('organization_city', sa.String(length=100), nullable=False))
    op.add_column('tbl_organizations', sa.Column('organization_timezone', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_organizations', 'organization_timezone')
    op.drop_column('tbl_organizations', 'organization_city')
    op.drop_column('tbl_organizations', 'organization_state')
    op.drop_column('tbl_organizations', 'organization_country')
    op.drop_column('tbl_organizations', 'organization_type')
    # ### end Alembic commands ###
