"""add classrooms module

Revision ID: c770538dddff
Revises: 005_uniq_ws_name_per_org
Create Date: 2026-08-10 18:25:59.196596+00:00

"""
from typing import Sequence, Union
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text, table, column


# revision identifiers, used by Alembic.
revision: str = 'c770538dddff'
down_revision: Union[str, Sequence[str], None] = '005_uniq_ws_name_per_org'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_classrooms',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('classroom_workspace_id', sa.UUID(), nullable=False),
    sa.Column('classroom_name', sa.String(length=255), nullable=False),
    sa.Column('classroom_description', sa.Text(), nullable=True),
    sa.Column('classroom_status', sa.Enum('active', 'archived', name='classroom_status_enum'), nullable=False),
    sa.Column('classroom_created_by', sa.UUID(), nullable=True),
    sa.Column('classroom_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classroom_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classroom_created_by'], ['tbl_users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classroom_workspace_id'], ['tbl_workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classroom_id'),
    sa.UniqueConstraint('classroom_workspace_id', 'classroom_name', name='uq_classroom_workspace_name')
    )
    op.create_index(op.f('ix_tbl_classrooms_classroom_workspace_id'), 'tbl_classrooms', ['classroom_workspace_id'], unique=False)
    op.create_table('tbl_classroom_members',
    sa.Column('classroom_member_id', sa.UUID(), nullable=False),
    sa.Column('classroom_member_classroom_id', sa.UUID(), nullable=False),
    sa.Column('classroom_member_user_id', sa.UUID(), nullable=False),
    sa.Column('classroom_member_type', sa.Enum('TEACHER', 'STUDENT', name='classroom_member_type_enum'), nullable=False),
    sa.Column('classroom_member_joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classroom_member_classroom_id'], ['tbl_classrooms.classroom_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_member_user_id'], ['tbl_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classroom_member_id'),
    sa.UniqueConstraint('classroom_member_classroom_id', 'classroom_member_user_id', name='uq_classroom_member')
    )
    # Seed new classroom permissions
    permissions_table = table(
        'tbl_permissions',
        column('permission_id', sa.UUID),
        column('permission_name', sa.String),
        column('permission_description', sa.Text),
        column('permission_created_at', sa.DateTime),
        column('permission_updated_at', sa.DateTime)
    )
    
    role_permissions_table = table(
        'tbl_role_permissions',
        column('role_permission_id', sa.UUID),
        column('role_id', sa.UUID),
        column('permission_id', sa.UUID),
        column('role_permission_created_at', sa.DateTime)
    )

    new_permissions = [
        ("classroom.read", "View classrooms"),
        ("classroom.delete", "Archive or delete classrooms"),
        ("classroom.member.add", "Add members to classrooms"),
        ("classroom.member.remove", "Remove members from classrooms"),
    ]

    permission_ids_map = {}
    for name, desc in new_permissions:
        perm_id = uuid.uuid4()
        permission_ids_map[name] = perm_id
        op.bulk_insert(
            permissions_table,
            [
                {
                    "permission_id": perm_id,
                    "permission_name": name,
                    "permission_description": desc,
                    "permission_created_at": datetime.now(timezone.utc),
                    "permission_updated_at": datetime.now(timezone.utc)
                }
            ]
        )

    # Map new permissions to existing system roles
    conn = op.get_bind()
    roles = conn.execute(text("SELECT role_id, role_name FROM tbl_roles WHERE role_organization_id IS NULL")).fetchall()
    roles_map = {r[1]: r[0] for r in roles}

    role_perms_mapping = {
        "Owner": ["classroom.read", "classroom.delete", "classroom.member.add", "classroom.member.remove"],
        "Admin": ["classroom.read", "classroom.delete", "classroom.member.add", "classroom.member.remove"],
        "Teacher": ["classroom.read", "classroom.member.add", "classroom.member.remove"],
        "Student": ["classroom.read"],
    }

    for role_name, perm_names in role_perms_mapping.items():
        role_id = roles_map.get(role_name)
        if not role_id:
            continue
        for pname in perm_names:
            pid = permission_ids_map.get(pname)
            if pid:
                op.bulk_insert(
                    role_permissions_table,
                    [
                        {
                            "role_permission_id": uuid.uuid4(),
                            "role_id": role_id,
                            "permission_id": pid,
                            "role_permission_created_at": datetime.now(timezone.utc)
                        }
                    ]
                )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text("DELETE FROM tbl_permissions WHERE permission_name IN ('classroom.read', 'classroom.delete', 'classroom.member.add', 'classroom.member.remove')"))
    op.drop_table('tbl_classroom_members')
    op.drop_index(op.f('ix_tbl_classrooms_classroom_workspace_id'), table_name='tbl_classrooms')
    op.drop_table('tbl_classrooms')
    # ### end Alembic commands ###
